# Generated by Django 5.2.7 on 2026-02-21 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0003_motorcycle_alter_car_table_car_photo_moto_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('application_type', models.CharField(choices=[('покупка', 'Покупка'), ('консультация', 'Консультация'), ('кредит', 'Кредит'), ('трейд-ин', 'Трейд-ин'), ('обратный_звонок', 'Обратный звонок')], max_length=50, verbose_name='Тип заявки')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='cars.car', verbose_name='Автомобиль')),
                ('motorcycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='cars.motorcycle', verbose_name='Мототехника')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'evaluations_application',
                'ordering': ['-created_at'],
            },
        ),
    ]
