# Generated by Django 5.2.7 on 2026-02-21 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.CharField(default='', max_length=100, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='car',
            name='drive_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Привод'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='car',
            name='marka',
            field=models.CharField(default='', max_length=100, verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Пробег'),
        ),
        migrations.AddField(
            model_name='car',
            name='price_byn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена BYN'),
        ),
        migrations.AddField(
            model_name='car',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена USD'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=50, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=2000, verbose_name='Год выпуска'),
        ),
    ]
