# Generated by Django 5.2.7 on 2026-02-21 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_options_car_available_car_body_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(default='', max_length=100, verbose_name='Марка')),
                ('moto_model', models.CharField(default='', max_length=100, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(default=2000, verbose_name='Год выпуска')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Пробег')),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Объём двигателя')),
                ('moto_type', models.CharField(blank=True, choices=[('мотоцикл', 'Мотоцикл'), ('квадроцикл', 'Квадроцикл'), ('скутер', 'Скутер')], max_length=50, verbose_name='Тип')),
                ('price_byn', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена BYN')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена USD')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Мототехника',
                'verbose_name_plural': 'Мототехника',
                'db_table': 'cars_motorcycle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelTable(
            name='car',
            table='cars_car',
        ),
        migrations.CreateModel(
            name='Car_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, verbose_name='Ссылка на фото')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Фото автомобиля',
                'verbose_name_plural': 'Фото автомобилей',
                'db_table': 'cars_car_photo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Moto_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, verbose_name='Ссылка на фото')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.motorcycle', verbose_name='Мототехника')),
            ],
            options={
                'verbose_name': 'Фото мототехники',
                'verbose_name_plural': 'Фото мототехники',
                'db_table': 'cars_moto_photo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='cars.car', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('motorcycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='cars.motorcycle', verbose_name='Мототехника')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'db_table': 'cars_favorite',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('car__isnull', False), ('motorcycle__isnull', False), _connector='OR'), name='favorite_car_or_moto'), models.UniqueConstraint(condition=models.Q(('car__isnull', False)), fields=('user', 'car'), name='unique_user_car'), models.UniqueConstraint(condition=models.Q(('motorcycle__isnull', False)), fields=('user', 'motorcycle'), name='unique_user_moto')],
            },
        ),
    ]
