# Generated by Django 5.2.7 on 2026-02-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_motorcycle_alter_car_table_car_photo_moto_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Объём двигателя'),
        ),
    ]
