# Generated by Django 5.2.7 on 2026-02-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_color_car_engine_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_photo',
            name='link',
        ),
        migrations.AddField(
            model_name='car_photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/photos/', verbose_name='Фото'),
        ),
    ]
