# Generated by Django 5.2.7 on 2026-02-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_photo_link_car_photo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto_photo',
            name='link',
        ),
        migrations.AddField(
            model_name='moto_photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='motorcycles/photos/', verbose_name='Фото'),
        ),
    ]
