# Generated by Django 5.2.7 on 2026-02-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_moto_photo_link_moto_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='engine_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Двигатель'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='transmission',
            field=models.CharField(blank=True, max_length=50, verbose_name='Привод'),
        ),
    ]
