# Generated by Django 5.2.7 on 2026-02-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_slug_motorcycle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='moto_type',
            field=models.CharField(blank=True, choices=[('мотоцикл', 'Мотоцикл'), ('квадроцикл', 'Квадроцикл'), ('скутер', 'Скутер'), ('седан', 'Седан')], max_length=50, verbose_name='Тип'),
        ),
    ]
